### ISSUE TITLE
Can't log in on http://localhost:3000/

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#18]
### To reproduce
* clone this repo
* npm install
* npm run build
* npm start
* go to http://localhost:3000
* click the house icon
* click 'Login'
* you get the popup
* select localhost:3000 as your IDP
* hit 'Go'

### Expected
You get the IDP login page where you can log in with 'foo@example.com' (any password).

### Actual
Nothing happens. In the developer tools you see:

Error: Error registering client: 400 Bad Request

**Comment by michielbdejong** [comment]
Ah ok, nevermind, it's a databrowser issue, not an IDP issue, so I'll fix this as part of #17

**Comment by jaxoncreed** [comment]
I just checked it out. For me it was because on localhost it doesn't run in https mode, and the idp doesn't like that.

**Comment by michielbdejong** [comment]
ah ok
