### ISSUE TITLE
proper content negotiation to determine whether or not to serve the data browser

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#2]
(ideally doing this through koa)

Follow-up from #1

**Comment by jaxoncreed** [comment]
Does this include the "If the container has an index.html then serve that instead" feature, or is it simply about content-type?

**Comment by michielbdejong** [comment]
No, this is only about content-types, in this case in the `Accept` header, we already use a library for parsing the ones in the `Content-Type` header.

**Comment by michielbdejong** [comment]
From the server's point of view, in the current situation, where the original representation is stored for LDP-RS as well as for LDP-NR there are always three options:
* serve the original representation
* serve an alternative RDF representation (at the wac-ldp level, done with `WacLdpTask#rdfTypeMatches`)
* serve an html page (at the pod-server level, using koa.accepts)
