### ISSUE TITLE
serve something on http://localhost:8080/

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#35]
When running this on data from a multi-user NSS install, I see the databrowser on e.g. http://michielbdejong.localhost:8080/ but I see a 404 on http://localhost:8080/.

**Comment by jaxoncreed** [comment]
Completed in the latest version with the following network configuration:

```js
{
  // ...
  "network": {
    "host": "localhost:8080",
    "port": 8080,
    "useHttps": false
  },
  // ...
}

```

**Comment by jaxoncreed** [comment]
Note that this configuration breaks OIDC standards as OIDC MUST be served over https
