### ISSUE TITLE
http://michielbdejong.localhost:8080/.well-known/openid-configuration missing

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#36]
http://localhost:8080/.well-known/openid-configuration exists, but
http://michielbdejong.localhost:8080/.well-known/openid-configuration gives a 401.

**Comment by jaxoncreed** [comment]
Ah. Tell me if you disagree, but I'd say that this is bad practice.

`http://michielbdejong.localhost:8080` is not an openid provider so it does not need a well-known. Instead, I think we should remove the feature that displays the current origin as an IDP option from `solid-auth-client`

**Comment by jaxoncreed** [comment]
Fixed in https://github.com/inrupt/pod-server/pull/39

**Comment by michielbdejong** [comment]
@jaxoncreed did you test this with an app? because I'm now seeing:

Access to fetch at 'http://michiel5.localhost:8080/.well-known/openid-configuration#me' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
