### ISSUE TITLE
email confirmation at sign-up

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#49]
NSS doesn't require you to confirm your email address when you sign up, but it's probably better to not allow use of the pod before the email has actually been validated?

**Comment by jaxoncreed** [comment]
I'd say this is an anti-pattern. As a rule in UX, you want to have the fewest number of steps to onboard a user. In fact many sites are even getting rid of "confirm password" fields. https://uxmovement.com/forms/why-the-confirm-password-field-must-die/
