### ISSUE TITLE
Consider not returning text/html content-type when cookie is set

### ISSUE THREAD

**Issue by michielbdejong** [inrupt/pod-server#5]
If a request to a resource has a cookie, then chances are that it's either an XHR or a straight browser tab request, from someone who is logged in to the data browser. In that case, it would be a bad idea to view html documents that were for instance sent to your inbox. To protect users against this making mistakes with this, and accidentally opening inbox messages that might try to access their data browser credentials, maybe we could configure the server not to server text/html content-type docs when the request has a cookie header. Instead, it serve a special html page with a data-browser logout button, and after that, the uploaded resource would become visible.

**Comment by Vinnl** [comment]
Note that the authentication token is not stored in a literal cookie, but [in localStorage](https://github.com/solid/solid-ui/blob/master/src/signin.js#L124). I'm not sure if that gets passed on through HTTP headers.

Alternatively, the session token could be stored in an [`HttpOnly` cookie](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies#Secure_and_HttpOnly_cookies) to prevent client-side scripts from accessing it, but that does require reworking the data browser.

**Comment by michielbdejong** [comment]
Cookies are currently only used by the IDP UI, so I think this is irrelevant. Please reopen if otherwise.
